Profile/urls.py
from django.urls import path

from .views import profile, profile_user_orders, profile_settings

app_name = 'profile'

urlpatterns = [
    path('profile', profile, name='profile'),
    path('profile/orders', profile_user_orders, name='orders'),
    path('profile/settings', profile_settings, name='settings'),

]

Profile/models.py
from django.db import models

# Create your models here.

Profile/forms.py
from django import forms


class UserEditProfileForm(forms.Form):
    first_name = forms.CharField(label='نام',
                                 widget=forms.TextInput(attrs={'class': 'form-control',
                                                               'placeholder': 'نام خود را وارد نمایید.'}),
                                 )

    last_name = forms.CharField(label='نام خانوادگی',
                                widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'placeholder': 'نام خانوادگی خود را وارد نمایید.'}),
                                )

    email = forms.EmailField(label='ایمیل',
                             widget=forms.EmailInput(attrs={'class': 'form-control',
                                                            'placeholder': 'ایمیل خود را وارد نمایید.'}),
                             )

Profile/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import render

from Orders.models import Order
from .forms import UserEditProfileForm


# Create your views here.
@login_required(login_url='/login')
def profile(request):
    context = {}
    return render(request, 'profile.html', context)


@login_required(login_url='/login')
def profile_user_orders(request):
    user_id = request.user.id
    orders = Order.objects.get(user_id=user_id)
    context = {}
    return render(request, 'profile_user_orders.html', context)


@login_required(login_url='/login')
def profile_settings(request):
    user_id = request.user.id
    user = User.objects.get(id=user_id)
    if user is None:
        raise Http404()

    edit_profile = UserEditProfileForm(request.POST or None,
                                       initial={'first_name': user.first_name,
                                                'last_name': user.last_name,
                                                'email': user.email})
    if edit_profile.is_valid():
        first_name = edit_profile.cleaned_data.get('first_name')
        last_name = edit_profile.cleaned_data.get('last_name')
        email = edit_profile.cleaned_data.get('email')

        user.first_name = first_name
        user.last_name = last_name
        user.email = email

        user.save()

    context = {
        'edit_profile': edit_profile
    }
    return render(request, 'profile_settings.html', context)


@login_required(login_url='/login')
def profile_sidebar(request):
    context = {}
    return render(request, 'profile_sidebar.html', context)

Profile/templates/profile.html
{% extends 'base/base.html' %}
{% load render_partial %}

{% block contents %}

    <div id="container">
    <div class="container">
      <div class="row">

        <!--Right Part Start -->
        <aside id="column-right" class="col-sm-3 hidden-xs">
            {% render_partial 'Profile.views.profile_sidebar' %}
        </aside>
        <!--Right Part End -->


        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
          <h1 class="title">پنل کاربر</h1>
          <br>
          <div class="row products-category">
              {% for product in page_obj %}
                  {% include 'product_item_component.html' with product=product %}
              {% endfor %}
          </div>
          <div class="row">
            <div class="col-sm-6 text-left">
              <ul class="pagination">
                  {% if page_obj.has_previous %}
                      <li><a href="?page={{ page_obj.previous_page_number }}">صفحه قبل</a></li>
                  {% endif %}
                  {% for page in paginator.page_range %}
                      {% if page == page_obj.number %}
                        <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                      {% else %}
                        <li><a href="?page={{ page }}">{{ page }}</a></li>
                      {% endif %}
                  {% endfor %}
                  {% if page_obj.has_next %}
                      <li><a href="?page={{ page_obj.next_page_number }}">صفحه بعد</a></li>
                  {% endif %}
              </ul>
            </div>
          </div>
        </div>
        <!--Middle Part End -->

      </div>
    </div>
  </div>

{% endblock %}

Profile/templates/profile_settings.html
{% extends 'base/base.html' %}
{% load render_partial %}

{% block contents %}

    <div id="container">
    <div class="container">
      <div class="row">

        <!--Right Part Start -->
        <aside id="column-right" class="col-sm-3 hidden-xs">
            {% render_partial 'Profile.views.profile_sidebar' %}
        </aside>
        <!--Right Part End -->


        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
          <h1 class="title">تنظیمات</h1>
            <form class="form-horizontal" method="post">
              {% csrf_token %}
            <fieldset>
              <div class="form-group required">
                <label class="col-md-2 col-sm-3 control-label" for="input-name">{{ edit_profile.first_name.label }}</label>
                <div class="col-md-10 col-sm-9">
                  {{ edit_profile.first_name }}
                </div>
                  {% for error in edit_profile.first_name.errors %}
                      <div class="text-danger">{{ error }}</div>
                  {% endfor %}
              </div>

              <div class="form-group required">
                <label class="col-md-2 col-sm-3 control-label" for="input-name">{{ edit_profile.last_name.label }}</label>
                <div class="col-md-10 col-sm-9">
                  {{ edit_profile.last_name }}
                </div>
                  {% for error in edit_profile.last_name.errors %}
                      <div class="text-danger">{{ error }}</div>
                  {% endfor %}
              </div>

              <div class="form-group required">
                <label class="col-md-2 col-sm-3 control-label" for="input-name">{{ edit_profile.email.label }}</label>
                <div class="col-md-10 col-sm-9">
                  {{ edit_profile.email }}
                </div>
                  {% for error in edit_profile.email.errors %}
                      <div class="text-danger">{{ error }}</div>
                  {% endfor %}
              </div>


            </fieldset>
            <div class="buttons">
              <div class="pull-right">
                <input class="btn btn-primary" type="submit" value="ارسال" />
              </div>
            </div>
          </form>
        </div>
        <!--Middle Part End -->

      </div>
    </div>
  </div>

{% endblock %}

Profile/templates/profile_sidebar.html
<ul>
    <li>
        <a href="/profile">پنل کاربر</a>
    </li>
    <li>
        <a href="{% url 'profile:orders' %}">سفارش های من</a>
    </li>
    <li>
        <a href="{% url 'profile:settings' %}">تنظیمات</a>
    </li>
    <li>
        <a href="/logout">خروج</a>
    </li>
</ul>

Profile/templates/profile_user_orders.html
{% extends 'base/base.html' %}
{% load render_partial %}

{% block contents %}

    <div id="container">
    <div class="container">
      <div class="row">

        <!--Right Part Start -->
        <aside id="column-right" class="col-sm-3 hidden-xs">
            {% render_partial 'Profile.views.profile_sidebar' %}
        </aside>
        <!--Right Part End -->


        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
          <h1 class="title">سفارش های من</h1>
        </div>
        <!--Middle Part End -->

      </div>
    </div>
  </div>

{% endblock %}