DjangoShop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from DjangoShop import settings
from .views import home, header, footer, login_page, register_page, logout_page
from Products.views import ProductListView, product_categories_partial
from Contact.views import contact_us

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('header', header, name='header'),
    path('footer', footer, name='footer'),
    path('contact-us', contact_us, name='contact'),
    path('login', login_page, name='login'),
    path('register', register_page, name='register'),
    path('logout', logout_page, name='logout'),
    path('', include('Products.urls', namespace='products')),
    path('', include('Orders.urls', namespace='orders')),
    path('', include('Profile.urls', namespace='profile')),
    path('product_categories_partial', product_categories_partial, name='product_categories_partial')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Orders/urls.py
from django.urls import path

from Orders.views import add_new_order, cart, remove_order
# , send_request, verify)

app_name = 'orders'

urlpatterns = [
    path('add-new-order', add_new_order),
    path('cart', cart, name='cart'),
    path('remove-order/<detail_id>', remove_order),
    # path('request/', send_request, name='request'),
    # path('verify/<order_id>', verify, name='verify'),
]

Products/urls.py
from django.urls import path
from django.contrib import admin
from .views import ProductListView, product_detail, SearchProducts, ProductListByCategory, product_categories_partial


app_name = 'products'

urlpatterns = [
    path('products', ProductListView.as_view(), name='products_list'),
    path('products/<product_id>/<title>', product_detail, name='product_detail'),
    path('products/search', SearchProducts.as_view()),
    path('products/<category_name>', ProductListByCategory.as_view()),
    path('admin/', admin.site.urls),
]

Profile/urls.py
from django.urls import path

from .views import profile, profile_user_orders, profile_settings

app_name = 'profile'

urlpatterns = [
    path('profile', profile, name='profile'),
    path('profile/orders', profile_user_orders, name='orders'),
    path('profile/settings', profile_settings, name='settings'),

]

templates/base/footer.html
{% load static %}
<!--Footer Start-->
  <footer id="footer">
    <div class="fpart-first">
      <div class="container">
        <div class="row">
          <div class="contact col-lg-8 col-md-8 col-sm-24 col-xs-24">
            <h5>اطلاعات تماس</h5>
            <ul>
              <li class="address"><i class="fa fa-map-marker"></i>{{ setting.address }}</li>
              <li class="mobile"><i class="fa fa-phone"></i>{{ setting.mobile }}</li>
              <li class="mobile"><i class="fa fa-fax"></i>{{ setting.fax }}</li>
              <li class="email"><i class="fa fa-envelope"></i>برقراری ارتباط از طریق <a href="{% url 'contact' %}">تماس با ما</a>
            </ul>
          </div>
          <div class="column col-lg-2 col-md-2 col-sm-3 col-xs-12">
            <h5>اطلاعات</h5>
            <ul>
              <li><a href="{% url 'home' %}">درباره ما</a></li>
              <li><a href="{% url 'home' %}">حریم خصوصی</a></li>
              <li><a href="{% url 'home' %}">شرایط و قوانین</a></li>
            </ul>
          </div>
          <div class="column col-lg-2 col-md-2 col-sm-3 col-xs-12">
            <h5>خدمات مشتریان</h5>
            <ul>
              <li><a href="{% url 'contact' %}">تماس با ما</a></li>
              <li><a href="{% url 'home' %}">بازگشت</a></li>
              <li><a href="{% url 'home' %}">نقشه سایت</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="fpart-second">
      <div class="container">
        <div id="powered" class="clearfix">
          <div class="powered_text pull-left flip">
            <p>{{ setting.copy_right }}</p>
          </div>
          <div class="social pull-right flip">
              <a href="{{ setting.instagram }}" target="_blank"> <img data-toggle="tooltip" src="{% static 'image/socialicons/instagram.png' %}" alt="Instagram" title="Instagram"> </a>
          </div>
        </div>
        <div class="bottom-row">
          <div class="custom-text text-center">
            <p>{{ setting.about }}</p>
          </div>
            <br>
        </div>
      </div>
    </div>
    <div id="back-top"><a data-toggle="tooltip" title="بازگشت به بالا" href="javascript:void(0)" class="backtotop"><i class="fa fa-chevron-up"></i></a></div>
  </footer>
  <!--Footer End-->
</div>
<!-- JS Part Start-->
<script type="text/javascript" src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.easing-1.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.dcjqaccordion.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
<!-- JS Part End-->
</body>
</html>

templates/base/header.html
{% load render_partial %}
{% load static %}

<!DOCTYPE html>
<html dir="rtl">
<head>
<meta charset="UTF-8" />
<meta name="format-detection" content="telephone=no" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href="{% static 'image/favicon.png' %}" rel="icon" />
<title>آنلاین شاپ</title>
<meta name="description" content="Responsive and clean html template design for any kind of ecommerce webshop">
<!-- CSS Part Start-->
<link rel="stylesheet" type="text/css" href="{% static 'js/bootstrap/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'js/bootstrap/css/bootstrap-rtl.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.transitions.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet-rtl.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/responsive-rtl.css' %}" />
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans' type='text/css'>
<!-- CSS Part End-->
</head>
<body>
<div class="wrapper-wide">
  <div id="header">
    <!-- Top Bar Start-->
    <nav id="top" class="htop">
      <div class="container">
        <div class="row"> <span class="drop-icon visible-sm visible-xs"><i class="fa fa-align-justify"></i></span>
          <div class="pull-left flip left-top">
            <div class="links">
              <ul>
                <li class="mobile"><i class="fa fa-phone"></i>{{ setting.phone }}</li>
                <li class="email"><a href="mailto:{{ setting.email }}"><i class="fa fa-envelope"></i>{{ setting.email }}</a></li>
              </ul>
            </div>
          </div>
          <div id="top-links" class="nav pull-right flip">
            <ul>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">خروج</a></li>
                    <li><a href="{% url 'profile:profile' %}">حساب کاربری</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">ورود</a></li>
                    <li><a href="{% url 'register' %}">ثبت نام</a></li>
                {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <!-- Top Bar End-->
    <!-- Header Start-->
    <header class="header-row">
      <div class="container">
        <div class="table-container">
          <!-- Logo Start -->
          <div class="col-table-cell col-lg-6 col-md-6 col-sm-12 col-xs-12 inner">
            <div id="logo"><a href="{% url 'home' %}"><img class="img-responsive" src="{{ setting.logo.url }}" title="فروشگاه ما" alt="فروشگاه ما" /></a></div>
          </div>
          <!-- Logo End -->
          <!-- Mini Cart Start-->
          <div class="col-table-cell col-lg-3 col-md-3 col-sm-6 col-xs-12">
          </div>
          <!-- Mini Cart End-->
          <!-- جستجو Start-->
          <div class="col-table-cell col-lg-3 col-md-3 col-sm-6 col-xs-12 inner">
            <div id="search" class="input-group">
              <form action="products/search" method="get">
                  <input id="filter_name" name="q" type="text" value="{{ request.GET.q }}" placeholder="جستجو" class="form-control input-lg" />
                  <button type="button" class="button-search"><i class="fa fa-search"></i></button>
              </form>
            </div>
          </div>
          <!-- جستجو End-->
        </div>
      </div>
    </header>
    <!-- Header End-->

    <!-- Main Start-->
    <div class="container">
      <nav id="menu" class="navbar">
        <div class="navbar-header"> <span class="visible-xs visible-sm"> منو <b></b></span></div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><a class="home_link" title="خانه" href="{% url 'home' %}"><span>خانه</span></a></li>
            <li><a class="" title="فروشگاه" href="{% url 'products:products_list' %}"><span>فروشگاه</span></a></li>
              <li class="mega-menu dropdown"><a>دسته بندی محصولات</a>
              <div class="dropdown-menu">
                  {% render_partial 'product_categories_partial' %}
            <li class="custom-link"><a href="{% url 'orders:cart' %}">سبد خرید</a></li>
            <li class="custom-link"><a href="#">صفحه پرداخت</a></li>
            <li class="contact-link"><a href="{% url 'contact' %}">تماس با ما</a></li>
            <li class="custom-link-right"><a href="{% url 'products:products_list' %}" target="_blank"> همین حالا بخرید!</a></li>
          </ul>
        </div>
      </nav>
    </div>
    <!-- Main End-->
  </div>